# Global configuration
[global]
checkNewVersion = false
sendAnonymousUsage = false

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
[entryPoints.web]
address = ":80"

#[entryPoints.websecure]
#address = ":443"


[log]
level = "DEBUG"
format = "common"

################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
[api]
insecure = true
dashboard = true

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[providers.docker]
endpoint = "unix:///var/run/docker.sock"
defaultRule = "Host(`{{ normalize .Name }}.malcherczyk.localhost`)"
exposedByDefault = true
watch = true

[http]
    [http.routers]
        [http.routers.vue]
            rule = "Host(`vue.malcherczyk.localhost`)"
            # If the rule matches, forward to the whoami service (declared below)
            service = "whoami"
    [http.services]
    # Define how to reach an existing service on our infrastructure
        [http.services.vue.loadBalancer]
            [[http.services.vue.loadBalancer.servers]]
                url = "http://private/vue-service"
